# Generated by Django 2.2 on 2019-04-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20190406_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'resolved'), (2, 'pending')], default=2),
        ),
    ]
