# Generated by Django 2.2 on 2019-04-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_lostandfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
