# Generated by Django 2.2 on 2019-04-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_lostandfound_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='requests.Student'),
        ),
    ]
