# Generated by Django 2.1.7 on 2019-04-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_post_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Menzies', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='reward',
            field=models.CharField(default='REWARD: $5', max_length=100),
        ),
    ]
