# Generated by Django 2.1.7 on 2019-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_auto_20190406_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='images/garden-locations-map.jpg', upload_to='images/'),
        ),
    ]
