# Generated by Django 2.1.7 on 2019-04-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='when',
            field=models.CharField(default='2:00pm - 4:00pm 7/4/2019', max_length=100),
        ),
    ]
